# Site settings
title: Bruno Orlandi
header-img: img/home-bg.jpg
email: brorlandi@gmail.com
copyright_name: Bruno Orlandi
description: > # this means to ignore newlines until "baseurl:"
  Site pessoal de Bruno Orlandi. 
  Formado em Ciências de Computação pela USP São Carlos, desenvolvedor Web full-stack.
  Organizando um portifólio e compartilhando minhas experiências. ;)
baseurl: ""
url: "https://brorlandi.github.io"
#twitter_username: 
github_username:  brorlandi
#facebook_username:  
email_username:  brorlandi@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: 
  - jekyll-paginate
  - jekyll-feed

timezone: America/Sao_Paulo